FORMAT: 1A
HOST: http://evented.apiary-mock.com

# Evented
Events from around the Dayton region aggregated

## Key Resources
* **Events**: Events that are occuring
* **Sources**: Sources (on the web) of events which are ingested into the system.

# Group Events
Events that are happening. This resource is *READ-ONLY*.

## GET /events?{complete,q,start,limit,order}
Returns a collection of events matching specified criteria
+ Parameters
    + complete = `false` (optional, string) ... True if complete events should be included in the results, false otherwise.
        +Values
            + `true`
            + `false`
    + q (optional, string) ... A free-text string
    + start=`1` (optional, number) ... Starting index
    + limit=`20` (optional, number) ... Number of items to return. ***Maximum value is 200***
    + order=`asc` (optional, text) ... Sort order of collection response

        + Values
            + `asc`
            + `desc`
+ Response 200 (application/json)

        [
            {
            "id":123,
            "source_url":"http://events.foo.org",
            "title":"someevent",
            "location":"711 e monument ave, Dayton, OH ",
            "date":"",
            "time":"",
            },
            {
            },
            {
            }
        
        ]

## GET /event/{id}
Find an event by id
+ Parameter
    + id (required, number) ... the unique identifier of the event
+ Response 200 (application/hal+json)
    
        {"some":"event"
        }

# Group Sources
Sources being included for aggregation. This resource is *READ-ONLY*.

## GET /sources?{start,limit}
A collection of sources
+ Parameter
    + start=`1` (optional, number) ... Starting index
    + limit=`20` (optional, number) ... Number of items to return. ***Maximum value is 200***
    
+ Response 200 (application/hal+json)

        [
        {},
        {}
        ]

## GET /sources/{id}
An individual source.
+ Parameter
    + id (required, number) ... The unique source id
+ Response 200 (application/hal+json)

        {"to":"do"
        }